apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql:
    USE mydb;
    CREATE TABLE product (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(20),
        description VARCHAR(100),
        price DECIMAL(8 , 3 )
    );
    CREATE TABLE coupon (
        id INT AUTO_INCREMENT PRIMARY KEY,
        code VARCHAR(20) UNIQUE,
        discount DECIMAL(8 , 3 ),
        exp_date VARCHAR(100)
    );