apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-mysql # since the coupon and product service images refer to mysql with this name
  labels:
    app: docker-mysql
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: docker-mysql
  template:
    metadata:
      labels:
        app: docker-mysql
    spec:
      volumes:
        - name: mysql-initdb-vol
          configMap:
            name: mysql-initdb-config
      containers:
        - name: docker-mysql
          image: mysql
          env:
            - name: MYSQL_DATABASE
              value: mydb
            - name: MYSQL_ROOT_PASSWORD
              value: r0oT1727
            - name: MYSQL_ROOT_HOST
              value: '%'
          volumeMounts:
            - name: mysql-initdb-vol
              mountPath: /docker-entrypoint-initdb.d