apiVersion: v1
kind: Service
metadata:
  name: product-app-svc
  labels:
    app: product-app
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30289
  selector:
    app: product-app