apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebserver
  labels:
    app: httpd
spec:
  replicas: 2
  # strategy: 
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxSurge: 3
  #     maxUnavailable: 4
  selector: 
    matchLabels: 
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 80
          volumeMounts:
            - name: demovol
              mountPath: /data #can be any directory in the container
            - name: demo-configmap-vol
              mountPath: /etc/myconfigs
            - name: my-secret # <=========== Secret mount
              mountPath: /etc/mysecrets
            - name: demo-pvc-vol # <=========== pvc mount
              mountPath: /my-pvc
      volumes:
        - name: demovol
          hostPath:
            path: /var/lib/docker/volumes/mywebserver-vol
            type: DirectoryOrCreate
        - name: demo-configmap-vol
          configMap:
            name: demo-configmap
        - name: my-secret # <=========== Secret volume
          secret:
            secretName: demo-secret
        - name: demo-pvc-vol # <=========== pvc volume
          persistentVolumeClaim: 
            claimName: demo-pvc
              